name: github-pages-build
on:
  push:
    tags:
      - 'v*'
jobs:
  Build-Create-Upload-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies & Build 
        run: |
         npm i
         npm install -g @angular/cli
         npm run build
         TIMESTAMP=$(date +%s)
         VERSION=$(npm pkg get version | sed 's/"//g')
         tar -czf PORTFOLIO-BUILD-$TIMESTAMP-$VERSION.gz dist/portfolio
         ls -ltr . 
         echo "ARTIFACT_FILE=PORTFOLIO-BUILD-$TIMESTAMP-$VERSION.gz" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Portfolio Build
          draft: false
          prerelease: false 

      - name: Upload Website Build
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_FILE }}
          asset_name: ${{ env.ARTIFACT_FILE }}
          asset_content_type: application/gzip