name: github-pages-build
on:
  push:
    branches:
    - automation-builds
    # Only run job on tags being pushed!
    tags:
      - v*.*.*

jobs:
  Build-Create-Upload-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "ðŸ this job's status is ${{ job.status }}."
      - name: Install dependencies & Build 
        run: |
         npm i
         npm install -g @angular/cli
         npm run build
         TIMESTAMP=$(date +%s)
         VERSION=$(npm pkg get version | sed 's/"//g')
         tar -czf PORTFOLIO-BUILD-$TIMESTAMP-$VERSION.gz dist/portfolio
         ls -ltr . 
         echo "ARTIFACT_FILE=PORTFOLIO-BUILD-$TIMESTAMP-$VERSION.gz" >> $GITHUB_ENV
      - name: Upload Artifact to Github repo 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_FILE }} 
          path: ./${{ env.ARTIFACT_FILE }} 

         
