name: github-pages-build
on:
  push:
    tags:
      - v*.*.*
    branches: 
      - automation-builds 

jobs:
  Build-Create-Upload-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "ðŸ this job's status is ${{ job.status }}."
      - name: Install dependencies & Build 
        run: |
         npm i
         npm install -g @angular/cli
         npm run build
         TIMESTAMP=$(date +%s)
         VERSION=$(npm pkg get version | sed 's/"//g')
         tar -czf PORTFOLIO-BUILD-$TIMESTAMP-$VERSION.gz dist/portfolio
         ls -ltr . 
         echo "ARTIFACT_FILE=PORTFOLIO-BUILD-$TIMESTAMP-$VERSION.gz" >> $GITHUB_ENV
      
      - name: Upload Website Build
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_FILE }}
          asset_name: ${{ env.ARTIFACT_FILE }}
          asset_content_type: application/gzip

      - name: Publish release 
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }} 
         
